apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: architecture
  description: The archi team
  annotations:
    backstage.io/techdocs-ref: dir:.  
spec:
  type: team
  profile:
    displayName: Architecture
    email: architecture@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  #parent: ops
  children: []
  members: [her, teby, emi, juan]    