apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testJP
  description: My component test
  annotations:
    backstage.io/techdocs-ref: dir:.   
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  providesApis:
    - artist-api  