# Group:
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: architecture
  description: The archi team 
spec:
  type: team
  profile:
    displayName: Architecture
    email: architecture@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  #parent: ops
  children: []
---
# Component:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: architecture-adr
  description: Architecture Decisions Records
  title: Architecture Decisions Records (ADR's)
  #labels:
  #tags:
  annotations:
    backstage.io/techdocs-ref: dir:.    
spec:
  type: adr
  lifecycle: experimental
  owner: group:architecture 